modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "true_end"
version = "${version}"
displayName = "True End"
authors = "Mystic Creations Team"
description = '''

'''
logoFile = "icon.png"

[[dependencies.true_end]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.true_end]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.true_end]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.true_end]]
modId = "terrablender"
mandatory = true
versionRange = "[3.0.1.10,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.true_end]]
modId = "nostalgic_tweaks"
mandatory = false
ordering = "AFTER"
versionRange = "2.0.0-beta.910"
side = "BOTH"